using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Focar.Helpers
{
    public class PomodoroMensagensDescanso
    {
		private readonly string[] _frases =
	  {
		"PARA DE TRABALHAR, ANIMAL. É HORA DE DESCANSAR.",
		"LARGA ESSA PORRA DESSE COMPUTADOR E VAI RESPIRAR UM AR QUE NÃO SEJA DE ESCRITÓRIO.",
		"ACABOU O POMODORO, JUMENTO. LEVANTA ESSA BUNDA DA CADEIRA.",
		"VAI DESCANSAR, DESGRAÇADO. O CÓDIGO NÃO VAI FUGIR.",
		"SEU CÉREBRO JÁ ESTÁ FUMANDO. PARA ANTES QUE ELE ABRA UM PROCESSO CONTRA VOCÊ.",
		"CHEGA DE TRABALHAR IGUAL UM OTÁRIO. É HORA DE PAUSAR.",
		"POMODORO ENCERRADO. AGORA VAI FAZER QUALQUER COISA QUE NÃO ENVOLVA TELA, SEU ANIMAL.",
		"DESCANSA, PORRA. VOCÊ NÃO GANHA BÔNUS POR FICAR OLHANDO PARA O CÓDIGO COM CARA DE DERROTADO.",
		"LEVANTA. ANDA. BEBE ÁGUA. FAZ ALGUMA COISA. SÓ NÃO FICA AÍ IGUAL UM MÓVEL.",
		"HORA DE RELAXAR, CAMPEÃO. ATÉ COMPUTADOR TEM COOLER E VOCÊ ACHA QUE NÃO PRECISA DE PAUSA?",
		"PARA AGORA. SE CONTINUAR TRABALHANDO DESSE JEITO, O PRÓXIMO BUG VAI SER VOCÊ.",
		"DESCANSO OBRIGATÓRIO, SEU DESGRAÇADO PRODUTIVO.",
		"LARGA O TECLADO. ELE NÃO TE AMA.",
		"VOCÊ NÃO É ESCRAVO DO POMODORO. AGORA SOME DA FRENTE DESSE PC.",
		"VAI TOMAR ÁGUA, PORRA. CAFÉ NÃO É SISTEMA HIDRÁULICO.",
		"ACABOU. FECHA ESSA IDE, SEU GOBLIN DE CÓDIGO.",
		"SEU TEMPO ACABOU, JUMENTO. SALVA O QUE FEZ E VAI DESCANSAR.",
		"NÃO, VOCÊ NÃO VAI 'SÓ TERMINAR ISSO'. VOCÊ SEMPRE FALA ISSO E DUAS HORAS DEPOIS ESTÁ NO MESMO LUGAR.",
		"VAI PAUSAR, FILHO DA TECNOLOGIA. O MUNDO SOBREVIVE SEM VOCÊ POR CINCO MINUTOS.",
		"PARABÉNS, VOCÊ SOBREVIVEU A MAIS UM POMODORO. AGORA VAI SENTAR EM OUTRO LUGAR E NÃO FAZER PORRA NENHUMA.",
		"HORA DO DESCANSO. SEU CÉREBRO ESTÁ RODANDO A 2 FPS.",
		"CHEGA DE CODAR, DESGRAÇA. ATÉ O COMPILADOR ESTÁ COM PENA DE VOCÊ.",
		"VAI DAR UMA VOLTA. VOCÊ JÁ ESTÁ COMEÇANDO A CONFUNDIR BUG COM FUNCIONALIDADE.",
		"PAUSA, ANIMAL. PRODUTIVIDADE SEM DESCANSO É SÓ CANSAÇO COM MARKETING.",
		"TIRA A MÃO DO MOUSE E VAI DESCANSAR, SEU VICIADO EM TAREFA.",
		"O POMODORO ACABOU. SE VOCÊ IGNORAR, EU VOU CONSIDERAR ISSO UMA AGRESSÃO AO SEU PRÓPRIO CÉREBRO.",
		"PARA DE SE TORTURAR. NEM O STACK OVERFLOW QUER TE VER TRABALHANDO AGORA.",
		"DESCANSA ESSA CARCAÇA. DEPOIS VOCÊ VOLTA A FINGIR QUE SABE O QUE ESTÁ FAZENDO.",
		"VAI RELAXAR, PORRA. SE TRABALHO FOSSE TUDO, SEU NOTEBOOK TERIA PLANO DE SAÚDE.",
		"ACABOU O POMODORO. AGORA SOME. É ORDEM."
	};

		private int _indice = 0;

		public string ProximaFrase()
		{
			var frase = _frases[_indice];
			_indice = (_indice + 1) % _frases.Length;

			return frase;
		}
	}

	public class PomodoroMensagensTrabalho
	{
		private readonly string[] _frases =
		{
		"ACABOU A MOLEZA, DESGRAÇADO. VOLTA A TRABALHAR.",
		"CHEGA DE DESCANSO, ANIMAL. O BOLETO NÃO VAI SE PAGAR SOZINHO.",
		"LEVANTA ESSA BUNDA E VOLTA PRO TRABALHO.",
		"FIM DA VIDA BOA, CAMPEÃO. HORA DE PRODUZIR.",
		"ACABOU O RECREIO, JUMENTO. VAMOS TRABALHAR.",
		"PARABÉNS PELO DESCANSO. AGORA VOLTA A FAZER COISA ÚTIL.",
		"O TEMPO DE FINGIR QUE ESTAVA DESCANSANDO ACABOU. VOLTA PRO CÓDIGO.",
		"CHEGA DE MOLEZA, PORRA. TEM BUG TE ESPERANDO.",
		"VOLTA PRO COMPUTADOR, GUERREIRO. A MERDA NÃO VAI SE RESOLVER SOZINHA.",
		"DESCANSOU? ÓTIMO. AGORA VAI TRABALHAR, SEU DESGRAÇADO.",
		"FIM DA PAUSA. SEU CÉREBRO JÁ FOI REINICIADO, AGORA USA ELE.",
		"LEVANTA, SACODE A POEIRA E VOLTA A PRODUZIR IGUAL UM CIDADÃO PAGADOR DE IMPOSTOS.",
		"ACABOU A FARRA. O POMODORO MANDOU VOLTAR AO BATENTE.",
		"A VIDA É FEITA DE PAUSAS E TRABALHO. INFELIZMENTE, AGORA É A PARTE DO TRABALHO.",
		"CHEGA DE CONTEMPLAR O TETO. TEM CÓDIGO PRA ESCREVER.",
		"SEU INTERVALO ACABOU. VOLTA PRA ESSA PORRA ANTES QUE O BUG SE MULTIPLIQUE.",
		"DESCANSO CONCLUÍDO COM SUCESSO. AGORA VAMOS NOVAMENTE SOFRER COM SOFTWARE.",
		"O CAFÉ ACABOU, A PAZ ACABOU E A PAUSA ACABOU. VOLTA A TRABALHAR.",
		"VAMOS, DESGRAÇA. MAIS UM POMODORO E DEPOIS VOCÊ PODE VOLTAR A RECLAMAR.",
		"HORA DE VOLTAR À LUTA. O COMPUTADOR ESTÁ LIGADO E O PROBLEMA CONTINUA LÁ.",
		"ACORDA, GUERREIRO. O DESCANSO FOI BOM, MAS O SALÁRIO EXIGE ESFORÇO.",
		"VOLTA PRO BATENTE, SEU MONSTRO. TEM TAREFA TE OLHANDO COM CARA DE COBRANÇA.",
		"FIM DA PAZ. ABRE O PROJETO E VAMOS FAZER ESSA PORRA FUNCIONAR.",
		"VOCÊ JÁ DESCANSOU O SUFICIENTE. AGORA VAI LÁ E RESOLVE ESSA DESGRAÇA.",
		"POMODORO INVERTIDO: ACABOU A PAUSA, COMEÇOU O SOFRIMENTO.",
		"LEVANTA E VOLTA. SEU FUTURO EU ESTÁ CONTANDO COM VOCÊ, INFELIZMENTE.",
		"A PREGUIÇA FOI CANCELADA. O TRABALHO FOI RENOVADO POR MAIS 25 MINUTOS.",
		"BORA TRABALHAR, PORRA. DAQUI A POUCO TEM OUTRA PAUSA.",
		"CHEGA DE VIDA DE APOSENTADO. VOLTA PRO CÓDIGO.",
		"ATENÇÃO, FUNCIONÁRIO: SEU PERÍODO DE EXISTÊNCIA SEM PRODUTIVIDADE FOI ENCERRADO."
	};

		private int _indice = 0;

		public string ProximaFrase()
		{
			var frase = _frases[_indice];
			_indice = (_indice + 1) % _frases.Length;

			return frase;
		}
	}
}
